- name: install vmware workstation dependencies
  pacman: name={{ item }}
  with_items:
    - fuse
    - gtkmm
    - linux-headers
  become: yes

- name: template vmware systemd service
  template: src=vmware.service dest=/etc/systemd/system/vmware.service
  become: yes

- name: install vagrant vmware plugin (license required)
  command: /usr/bin/vagrant plugin install vagrant-vmware-workstation
  become: yes
  become_user: "{{ archlinux_username }}"

- name: vmware instructions
  debug: msg="Install VMWare Workstation manually with '/usr/bin/sh <vmware installer> --eulas-agreed --required --console'"
  when: archlinux_vmware|bool
